version: '3.8'

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/alternatives/my.cnf
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scooter
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    expose:
      - 3306
  app:
    depends_on:
      - db
    image: ghcr.io/bartosz-radtke-eclipse/scooter-rental-backend:${BRANCH}
    ports:
      - "8080:8080"
    expose:
      - 8080
    stdin_open: true
    tty: true
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/testscooter?autoReconnect=true&useSSL=false
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  db_data: {}